import React from 'react'
import styles from './styles.module.css'
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Bio",
  description: "Generated by create next app",
};

export default function BioLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
        <>
            <nav>About NavBar</nav>
            <main className={styles.main}>
                {children}
            </main>
        </>
  )
}
